version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - '${APP_PORT:-80}:8080'
    environment:
      APP_URL: '${APP_URL:-http://localhost:80}'
    volumes:
      - './media:/home/app/media'
      - './cache:/home/app/cache'
